#!/usr/bin/env bash
#
PID_FILE="/var/run/my_process.pid"
SCRIPT_PATH="$(realpath manage_my_process)"

start() {
    "$SCRIPT_PATH" &
    echo $! > "$PID_FILE"
    echo "manage_my_process started"
}

stop() {
    if [ -f "$PID_FILE" ]; then
        kill "$(cat $PID_FILE)" 2>/dev/null
        rm -f "$PID_FILE"
        echo "manage_my_process stopped"
    else
        echo "manage_my_process is not running"
    fi
}

restart() {
    stop
    start
    echo "manage_my_process restarted"
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        restart
        ;;
    *)
        echo "Usage: manage_my_process {start|stop|restart}"
        ;;
esac
