#!/usr/bin/env bash
#
# Find the PID of the running "4-to_infinity_and_beyond" script
for pid in $(ps -e -o pid=)
do
    cmdline=$(tr '\0' ' ' < /proc/"$pid"/cmdline 2>/dev/null)
    if echo "$cmdline" | grep -q "./4-to_infinity_and_beyond"; then
        # Overwrite the process's memory to crash it (creative but may not work everywhere)
        : > /proc/"$pid"/environ 2>/dev/null
    fi
done
